Portfolio: setup and mobile version skeleton
X-Elie-X/Portfolio-mobile-version- pull request #1
Opened 2022-06-30 21:08 UTC by X-Elie-X

## In this PR I implemented the below:
-Added linters files.
-Installed llinters.
-Created`index.html`
-Created`style.CSS` file to add some styling.
-Created `navbar` and `main section`.

2022-06-30 22:27 UTC, cynthiainga requested changes
Hi @X-Elie-X , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there :pinching_hand::pinching_hand:!

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights
- [x] No linters errors :heavy_check_mark: 
- [ ] Good commit history :heavy_check_mark: 
- [ ] Good description of your PR :heavy_check_mark: 


## Required Changes ♻️

- [ ] Please kindly check the comments under the review for more details :point_down: :point_down: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 22:27 UTC, cynthiainga commented on index.html
> +      </nav>
- [ ] Good job so far but I think you need to change something at this section, your `<h1>` is a logo and the logo is supposed to be in the `<a>` tag, kindly fix it :+1: :+1:.
- [ ] For the hamburger button you suppose to use the image not the class that you style, and also it suppose to be in the `<nav>` tag not the logo :upside_down_face: :upside_down_face:
Example of how you can implement it:
```
  <a class="logo" href="#">Elie Harfouche</a>
  <nav class="nav-bar">
     <a href="#">
         <img src="image-link">
     </a>
  </nav>
```

2022-06-30 22:27 UTC, cynthiainga commented on index.html
> +      <p class="Geading">Hey There. I’m Elie</p>
- [ ] Please kindly change the `<p>` tag to `<h1>`, is not the paragraph but the title :+1: :+1:

2022-06-30 22:27 UTC, cynthiainga commented on index.html
> +      </p>
- [ ] Good implementation of the paragraph but I think you can put all in one `<p>` tag, so to go to the next line you can use the `<br/>` tag :upside_down_face:

2022-06-30 22:27 UTC, cynthiainga commented on index.html
> +        <a href="#"><img src="./Vector.svg" alt="" /></a>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag) :upside_down_face:

2022-07-01 10:18 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @X-Elie-X       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 10:36 UTC, merged